server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-http-form-post-size: -1
    max-swallow-size: -1
#spring
spring:
  #mysql数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/jinops?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 183461
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      initial-size: 3
      max-active: 10
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  #热部署
  devtools:
    restart:
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
mybatis:
  #配置映射文件
  mapper-locations: classpath:com/hebeu/mapper/*.xml
  #配置实体类
  type-aliases-package: com.hebeu.model
  configuration:
#    #延迟加载
#    lazy-loading-enabled: true
#    #开启按需加载
#    aggressive-lazy-loading: false
    #打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file:
    path: backend/parent/manager/controller/src/main/resources/static/log
  level:
    root: info #日志级别 root表示所有包，也可以单独配置具体包 fatal error warn info debug trace off